version: '3'

volumes:
  winemate.catalog.database:
  winemate.reviews.database:

services: 
  winemage.gateway:
    container_name: "winemate-gateway"
    build: 
      context: .
      dockerfile: WineMate.Gateway/Dockerfile
    ports:
      - "8000:8080"
  
  winemate.catalog.app:
    container_name: "winemate-catalog-app"
    build: 
      context: .
      dockerfile: WineMate.Catalog/Dockerfile
    ports:
      - "8100:8080"
    depends_on:
      - winemate.catalog.database
      - winemate.rabbitmq
  
  winemate.catalog.database:
    container_name: "winemate-catalog-database"
    image: postgres:alpine
    environment:
      - POSTGRES_USER=superuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=winemate_catalog
    ports:
        - "8110:5432"
    volumes:
      - .containers/winemate.catalog.database/data:/var/lib/postgresql/data    
  
  winemate.reviews.app:
    container_name: "winemate-reviews-app"
    build: 
      context: .
      dockerfile: WineMate.Reviews/Dockerfile
    ports:
      - "8200:8080"
    depends_on:
      - winemate.reviews.database
      - winemate.rabbitmq
  
  winemate.reviews.database:
    container_name: "winemate-reviews-database"
    image: postgres:alpine
    environment:
      - POSTGRES_USER=superuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=winemate_reviews
    ports:
        - "8210:5432"
    volumes:
      - .containers/winemate.reviews.database/data:/var/lib/postgresql/data
        
  winemate.identity.app:
    container_name: "winemate-identity-app"
    build:
      context: .
      dockerfile: WineMate.Identity/Dockerfile
    ports:
      - "8300:8080"
    depends_on:
      - winemate.identity.database
      - winemate.rabbitmq

  winemate.identity.database:
    container_name: "winemate-identity-database"
    image: postgres:alpine
    environment:
      - POSTGRES_USER=superuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=winemate_identity
    ports:
      - "8310:5432"
    volumes:
      - .containers/winemate.identity.database/data:/var/lib/postgresql/data
      
  winemate.rabbitmq:
    container_name: "winemate-rabbitmq"
    image: rabbitmq:management
    ports:
      - "9100:5672"
      - "9150:15672"
    volumes:
      - .containers/winemate.rabbitmq/data:/var/lib/rabbitmq
      - .containers/winemate.rabbitmq/logs:/var/log/rabbitmq
    environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest