version: '3'

volumes:
  winemate.catalog.database:
  winemate.reviews.database:

services: 
  winemate.catalog.app:
    container_name: "winemate-catalog-app"
    build: 
      context: .
      dockerfile: WineMate.Catalog/Dockerfile
    ports:
      - "8100:8080"
    depends_on:
      - winemate.catalog.database
  
  winemate.catalog.database:
    container_name: "winemate-catalog-database"
    image: postgres:alpine
    environment:
      - POSTGRES_USER=superuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=winemate_catalog
    ports:
        - "8110:5432"
    volumes:
      - .containers/winemate.catalog.database/data:/var/lib/postgresql/data    
  
  winemate.reviews.app:
    container_name: "winemate-reviews-app"
    build: 
      context: .
      dockerfile: WineMate.Reviews/Dockerfile
    ports:
      - "8200:8080"
    depends_on:
      - winemate.reviews.database
  
  winemate.reviews.database:
    container_name: "winemate-reviews-database"
    image: postgres:alpine
    environment:
      - POSTGRES_USER=superuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=winemate_reviews
    ports:
        - "8210:5432"
    volumes:
      - .containers/winemate.reviews.database/data:/var/lib/postgresql/data
      
  winemate.rabbitmq:
    container_name: "winemate-rabbitmq"
    image: rabbitmq:management
    volumes:
      - .containers/winemate.rabbitmq/data:/var/lib/rabbitmq
      - .containers/winemate.rabbitmq/logs:/var/log/rabbitmq
    environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest